Type of injury prediction

In [43]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt  
import tensorflow as tf

In [44]:
dataset = pd.read_csv("merged.csv")

list1 = []
for i in range(len(dataset)):
    list1.append(0)
    if(dataset['DAYS MISSED'][i] >0):
        list1[i]=1
    else:
        list1[i]=0
dataset['injured check'] = list1

In [45]:
dataset['INJURED_TYPE'] = dataset['INJURED_TYPE'].fillna('No_injury')
print(dataset['INJURED_TYPE'])

0            No_injury
1            No_injury
2            No_injury
3       Sprained_ankle
4            No_injury
             ...      
5573         No_injury
5574         No_injury
5575         No_injury
5576         No_injury
5577         No_injury
Name: INJURED_TYPE, Length: 5578, dtype: object


In [46]:
X = dataset.iloc[:, 3:-6].values
X = X.tolist()
for i in range(len(X)):
    for j in range(len(X[i])):
        if(X[i][j] ==' None'):
            X[i][j] = 0
        if(type(X[i][j]) == str):
            X[i][j] = float(X[i][j])
X = np.array(X)
y = dataset.iloc[:, -2].values

In [47]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [48]:
class_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("Class Mapping:", class_mapping)
L = list(class_mapping.keys())
print(L)
unique_values_after_encoding = set(dataset['INJURED_TYPE'])
print("Unique Values in INJURED_TYPE After Label Encoding:", unique_values_after_encoding)

Class Mapping: {'Knee_injury': 0, 'No_injury': 1, 'Sore_ankle': 2, 'Sore_knee': 3, 'Sore_lower_back': 4, 'Sprained_ankle': 5}
['Knee_injury', 'No_injury', 'Sore_ankle', 'Sore_knee', 'Sore_lower_back', 'Sprained_ankle']
Unique Values in INJURED_TYPE After Label Encoding: {'Sore_knee', 'Sore_ankle', 'Knee_injury', 'Sore_lower_back', 'Sprained_ankle', 'No_injury'}


In [49]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [50]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [51]:
ann = tf.keras.models.Sequential()

In [52]:

ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))
ann.add(tf.keras.layers.Dense(units=100, activation='relu'))

In [53]:
num_classes = len(np.unique(y_train))
ann.add(tf.keras.layers.Dense(units=num_classes, activation='softmax'))

In [54]:
ann.compile(optimizer= 'adam', loss= 'sparse_categorical_crossentropy', metrics= ['accuracy'])

In [55]:
ann.fit(X_train, y_train, batch_size= 150, epochs= 400 , validation_data=(X_test, y_test))

Epoch 1/400


30/30 [==============================] - 2s 10ms/step - loss: 1.0471 - accuracy: 0.7580 - val_loss: 0.7346 - val_accuracy: 0.7858
Epoch 2/400
30/30 [==============================] - 0s 4ms/step - loss: 0.7406 - accuracy: 0.7815 - val_loss: 0.7150 - val_accuracy: 0.7858
Epoch 3/400
30/30 [==============================] - 0s 4ms/step - loss: 0.7203 - accuracy: 0.7815 - val_loss: 0.7085 - val_accuracy: 0.7858
Epoch 4/400
30/30 [==============================] - 0s 4ms/step - loss: 0.7074 - accuracy: 0.7815 - val_loss: 0.7108 - val_accuracy: 0.7858
Epoch 5/400
30/30 [==============================] - 0s 4ms/step - loss: 0.7085 - accuracy: 0.7815 - val_loss: 0.7052 - val_accuracy: 0.7858
Epoch 6/400
30/30 [==============================] - 0s 4ms/step - loss: 0.6977 - accuracy: 0.7815 - val_loss: 0.7003 - val_accuracy: 0.7858
Epoch 7/400
30/30 [==============================] - 0s 4ms/step - loss: 0.6794 - accuracy: 0.7815 - val_loss: 0.6956 - val_accuracy: 0.7858
Epoch 8/400
30/30 [=====

In [56]:
season_num = float(input("Numeric representation of the season played by the player:"))
age = int(input("Current age of the player:"))
PLAYER_HEIGHT_INCHES = int(input("The height of the player in inches:"))
PLAYER_WEIGHT = int(input("The weight of the player:"))
GP = int(input("the number of games in which the player participated:"))
MIN = float(input("Total minutes played by the player:"))
USG_PCT = float(input("an estimate of the percentage of team plays used by a player while on the court:"))
pace = float(input("The pace of play:"))
poss = int(input("the total number of offensive and defensive possessions:"))
FGA_PG = int(input("Field Goals Attempted per game:"))
DRIVES= float(input("The number of times a player drives towards the basket:"))
DRIVE_FGA =  float(input("Field Goals Attempted on drives:"))
DRIVE_PASSES = float(input("Passes made during drives:"))
DIST_MILES = float(input("Total distance covered by the player in miles:"))
AVG_SPEED = float(input("Average speed of the player in miles per hour:"))
PULL_UP_FGA = float(input("Field Goals Attempted on pull-up shots:"))
PULL_UP_FG3A = float(input("Three-Point Field Goals Attempted on pull-up shots:"))
TOUCHES = float(input("The number of times the player touched the ball:"))
FRONT_CT_TOUCHES = float(input("Front Court Touches - the number of times the player touched the ball in the frontcourt:"))
AVG_SEC_PER_TOUCH = float(input("Average seconds per touch:"))
AVG_DRIB_PER_TOUCH = float(input("Average dribbles per touch:"))
ELBOW_TOUCHES = float(input("The number of times the player touched the ball in the elbow area:"))
POST_TOUCHES = float(input("The number of times the player touched the ball in the post area:"))
PAINT_TOUCHES = float(input("The number of times the player touched the ball in the paint area:"))
TEAM = str(input("The team for which the player played during the specified season:"))
list2 = [season_num,age,PLAYER_HEIGHT_INCHES,PLAYER_WEIGHT,GP,MIN,USG_PCT,pace,poss,FGA_PG,DRIVES,DRIVE_FGA,DRIVE_PASSES,DIST_MILES,AVG_SPEED,PULL_UP_FGA,PULL_UP_FG3A,TOUCHES,FRONT_CT_TOUCHES,AVG_SEC_PER_TOUCH,AVG_DRIB_PER_TOUCH,ELBOW_TOUCHES,POST_TOUCHES,PAINT_TOUCHES]
#print(ann.predict((sc.transform([list2])))>0.5)
R = ann.predict((sc.transform([list2])))>0.5
for i in range(len(R[0])):
    if(R[0][i]== True):
        print("probable injury is: {}".format(L[i]))

1/1 [==============================] - 0s 100ms/step
probable injury is: No_injury


In [57]:
y_pred = np.argmax(ann.predict(X_test), axis=-1)
y_pred = (y_pred > 0.5)
y_pred = np.argmax(ann.predict(X_test), axis=-1)

35/35 [==============================] - 0s 969us/step


In [58]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print("Each column and each row is: ['Knee_injury', 'No_injury', 'Sore_ankle', 'Sore_knee', 'Sore_lower_back', 'Sprained_ankle']")
print(cm)
print("accuracy_score is:",accuracy_score(y_test, y_pred))

Each column and each row is: ['Knee_injury', 'No_injury', 'Sore_ankle', 'Sore_knee', 'Sore_lower_back', 'Sprained_ankle']
[[ 10   3   0   1   0   4]
 [  0 796   2  22   5  52]
 [  0   1   4   3   0   8]
 [  3  28   3  21   3  14]
 [  0   7   0   1   5   6]
 [  1  60   3  16   7  27]]
accuracy_score is: 0.7732974910394266
